parse_config:
  zmk_remove_keycode_prefix: ["DE_"]
  zmk_keycode_map:
    # custom mappings

    LCTRL: Ctrl
    RCTRL: Ctrl
    LALT: Alt
    RALT: AltGr
    LGUI: $$mdi:apple-keyboard-command$$
    RGUI: $$mdi:apple-keyboard-command$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    SPACE: $$mdi:keyboard-space$$
    BSPC: $$mdi:backspace$$
    RET: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    DEL: $$mdi:backspace-reverse-outline$$

    INS: Insert
    HOME: Home
    END: End
    CAPSLOCK: $$mdi:caps-lock$$
    PSCRN: Print Scrn
    PAUSE_BREAK: Pause Break

    # Arrows
    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$
    PG_UP: $$mdi:transfer-up$$
    PG_DN: $$mdi:transfer-down$$

    # Sound
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$

    # Media
    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$
    C_PP: $$mdi:play-pause$$

    # Bluetooth
    BT_CLR: $$mdi:bluetooth-off$$
    BT_SEL: $$mdi:bluetooth-connect$$
    bt_0: $$mdi:bluetooth-connect$$ test
    bt_1: $$mdi:bluetooth-connect$$

    # Settings
    C_BRI_UP: $$mdi:brightness-5$$
    C_BRI_DN: $$mdi:brightness-7$$

    DEGREE: '°'
    ACUTE: '´'

    U_UMLAUT: 'Ü'
    O_UMLAUT: 'Ö'
    A_UMLAUT: 'Ä'

    # defaults
    AMPERSAND: '&'
    AMPS: '&'
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ':'
    COMMA: ','
    DLLR: $
    DOLLAR: $
    DOT: '.'
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: '='
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    GRAVE: '`'
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    LBKT: '['
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: '-'
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RBKT: ']'
    RBRC: '}'
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: ''''
    SLASH: /
    SQT: ''''
    STAR: '*'
    TILDE: '~'
    TILDE2: '~'
    UNDER: _
    UNDERSCORE: _

draw_config:
  dark_mode: auto
