parse_config:
  zmk_remove_keycode_prefix: ["DE_"]
  mark_alternate_layer_activators: true
  raw_binding_map:
    # Bluetooth
    # "&bt_0": $$mdi:bluetooth-connect$$
    # "&bt_1": $$mdi:bluetooth-connect$$

    # Reset
    "&sys_reset": $$mdi:backup-restore$$
    "&bootloader": $$mdi:progress-download$$

  zmk_combos:
    combo_top_outer: {draw_separate: true}
    combo_mid_outer: {draw_separate: true}
    combo_bottom_outer: {draw_separate: true}

  zmk_keycode_map:
    # custom mappings

    LCTRL: Ctrl
    RCTRL: Ctrl
    LALT: Alt
    RALT: AltGr
    LGUI: $$mdi:apple-keyboard-command$$
    RGUI: $$mdi:apple-keyboard-command$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    SPACE: $$mdi:keyboard-space$$
    BSPC: $$mdi:backspace$$
    RET: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    DEL: $$mdi:backspace-reverse-outline$$

    INSERT: Insert
    HOME: Home
    END: End
    CAPSLOCK: $$mdi:caps-lock$$
    PRINTSCREEN: $$mdi:printer-pos-cog$$
    PAUSE_BREAK: $$mdi:cog-pause$$
    SCROLLLOCK: $$mdi:mouse-scroll-wheel$$
    C_AL_CALCULATOR: $$mdi:calculator$$

    # Arrows
    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$
    PG_UP: $$mdi:transfer-up$$
    PG_DN: $$mdi:transfer-down$$

    # Sound
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$

    # Media
    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$
    C_PP: $$mdi:play-pause$$

    # Bluetooth
    BT_CLR: $$mdi:bluetooth-off$$
    BT_SEL: $$mdi:bluetooth-connect$$

    # Settings
    C_BRI_UP: $$mdi:brightness-5$$
    C_BRI_DN: $$mdi:brightness-7$$

    DEGREE: '°'
    ACUTE: '´'

    # German
    U_UMLAUT: 'Ü'
    O_UMLAUT: 'Ö'
    A_UMLAUT: 'Ä'
    SZ: 'ß'

    # Numpad
    KP_N0: '0'
    KP_N1: '1'
    KP_N2: '2'
    KP_N3: '3'
    KP_N4: '4'
    KP_N5: '5'
    KP_N6: '6'
    KP_N7: '7'
    KP_N8: '8'
    KP_N9: '9'

    KP_NUM: $$mdi:numeric$$
    KP_EQUAL: '='
    KP_SLASH: '/'

    KP_MULTIPLY: '*'
    KP_PLUS: '+'
    KP_MINUS: '-'
    KP_ENTER: $$mdi:keyboard-return$$

    KP_DOT: '.'

    # defaults
    AMPERSAND: '&'
    AMPS: '&'
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ':'
    COMMA: ','
    DLLR: $
    DOLLAR: $
    DOT: '.'
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: '='
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    GRAVE: '`'
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    LBKT: '['
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: '-'
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RBKT: ']'
    RBRC: '}'
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: ''''
    SLASH: /
    SQT: ''''
    STAR: '*'
    TILDE: '~'
    TILDE2: '~'
    UNDER: _
    UNDERSCORE: _

draw_config:
  combo_diagrams_scale: 2
  dark_mode: auto
